config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { 
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    post '/trial-registration' => 'users/registrations#trial_registration'
  end

  namespace :users, path: "" do
    resources :missions
  end

  devise_for :admin, controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  namespace :admin do
    get :dashboard, to: "base#dashboard"
    get "dashboard/missions", to: "base#missions"
  end
  get '/successfully-registered', to: 'pages#successfully_registered'
  get '/already-registered', to: 'pages#already_registered'
  root 'pages#landing'
end

app/views/layouts/_admin_navbar.html.erb
<!-- Header -->
<header class="alt navbar navbar-default">
  <div class="container">
    <h1 class="navbar-brand" href="javascript:void(0)">
      <%= link_to root_path do %>
        Mission-Apartment<small><span class="badge" style="margin-bottom: 2em">alpha</span></small>
      <% end %>
    </h1>
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to("任務列表", admin_dashboard_missions_path) %></li>
    <li><%= link_to("登出", destroy_admin_session_path, method: :delete) %></li>
  </ul>
  <!-- <a href="#nav">Menu</a> -->
  </div>
</header>

<!-- Nav -->
<!-- <nav id="nav">
  <ul class="links">
    <li><a href="index.html">Home</a></li>
    <li><a href="generic.html">Generic</a></li>
    <li><a href="elements.html">Elements</a></li>
  </ul>
</nav> -->

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer id="footer" class="footer">
  <div class="inner">
    <ul class="icons">
      <li><a href="https://www.facebook.com/groups/872592962821382/" class="icon fa-facebook">
        <span class="label">Facebook</span>
      </a></li>
      <!-- <li><a href="#" class="icon fa-twitter">
        <span class="label">Twitter</span>
      </a></li>
      <li><a href="#" class="icon fa-instagram">
        <span class="label">Instagram</span>
      </a></li>
      <li><a href="#" class="icon fa-linkedin">
        <span class="label">LinkedIn</span>
      </a></li> -->
    </ul>
    <ul class="copyright">
      <li>&copy; Mission Apartment 視訊代客看屋服務</li>
    </ul>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<!-- Header -->
<header id="header" class="alt navbar navbar-default navbar-fixed-top">
  <h1>
  <%= link_to root_path do %>
    Mission-Apartment<small><span class="badge" style="margin-bottom: 2em">alpha</span></small>
  <% end %>
  </h1>
  <!-- <a href="#nav">Menu</a> -->
  <%= link_to("登入", new_user_session_path) %>
</header>

<!-- Nav -->
<!-- <nav id="nav">
  <ul class="links">
    <li><a href="index.html">Home</a></li>
    <li><a href="generic.html">Generic</a></li>
    <li><a href="elements.html">Elements</a></li>
  </ul>
</nav> -->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MissionApartment</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta property="og:image" content="<%= image_url('cover7.jpg') %>" />
  <%= csrf_meta_tags %>
</head>
<body class="landing">
<%= render "layouts/admin_navbar" %>
<div class="container">
  <%= yield %>
</div>
<%= render "layouts/footer" %>  
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MissionApartment</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta property="og:image" content="<%= image_url('cover7.jpg') %>" />
  <%= csrf_meta_tags %>
</head>
<body class="landing">
<%= render "layouts/navbar" %>
<%= yield %>
<%= render "layouts/footer" %>
</body>
</html>